### ISSUE TITLE
Nicolás Ruiz

### ISSUE THREAD

**Issue by OneNico** [gopimn/elo329_1_2022#13]
import java.util.Scanner;

public class DistanciaOrigen  {
    public static void main(String[] args) throws Exception {
        Scanner lector = new Scanner(System.in);
    

        System.out.print("Ingrese su coordenada en x: "); 
        int x = lector.nextInt();
        System.out.print("Ingrese su coordenada en y: "); 
        int y = lector.nextInt();
        System.out.print("Ingrese su coordenada en z: "); 
        int z = lector.nextInt();

        Punto a= new Punto(-1, 0, 4);
        Punto b= new Punto(x, y, z);

        if(a.equals(b))
            System.out.println("\nSu punto es el origen");
        else
            System.out.println("\nLa distancia desde su punto al origen es: " + a.distance(b));
        
        lector.close();
    }
}
class Punto{
    private int x, y, z;
    public Punto(){
        x = y = z = 0;
    }

    public Punto(int _x, int _y, int _z){
        x = _x;
        y = _y;
        z = _z;
    }

    public int getX(){
        return x;
    }

    public int getY(){
        return y;
    }

    public int getZ(){
        return z;
    }

    public boolean equals(Punto p){
        if(p == null)
            return false;
        return (x == p.getX()) && (y == p.getY()) && (z == p.getZ());
    }
    public double distance(Punto p){
        if(p == null)
            return -1;
        double delta_x = x - p.getX();
        double delta_y = y - p.getY();
        double delta_z = z - p.getZ();
    
        return (Math.sqrt(Math.pow(delta_x, 2) + Math.pow(delta_y, 2) + Math.pow(delta_z, 2)));
    }
}

**Comment by gopimn** [comment]
Hola Nicolás, bueno el codgo, 
```bash
test > javac test.java && java test
Ingrese su coordenada en x: 4
Ingrese su coordenada en y: 3
Ingrese su coordenada en z: 2

La distancia desde su punto al origen es: 6.164414002968976
```

Lo único es que no estas tomando el primer punto como el origen.

Acuérdate por favor de leeer [esta guía](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) para que formatees bien en los issues :dancers: 

Acuérdate también de postear el código en R3.
