### ISSUE TITLE
Andrés Pino Elier

### ISSUE THREAD

**Issue by Sarelier** [gopimn/elo329_1_2022#22]

**Comment by gopimn** [comment]
Hola Andres!

Te fue bien con el code?

**Comment by Sarelier** [comment]
#include <iostream>
 
int main () 
{
    std::cout << "Hola, mundo";
    return 0;
}

**Comment by Sarelier** [comment]
`#include <iostream>
 
int main () 
{
    std::cout << "Hola, mundo";
    return 0;
}`
