### ISSUE TITLE
Abraham Sanchez

### ISSUE THREAD

**Issue by infacundo** [gopimn/elo329_1_2022#3]
posdata: el main se llama maina por si acaso :D

import java.util.Scanner;  // Import the Scanner class

public class Maina {
    public static void main(String[] args) {
        Scanner reader = new Scanner(System.in);  // Create a Scanner object
        System.out.println("########## Jugando con puntos ######## \ningrese su abscisa(x)");
        int x = reader.nextInt();  // Read user input
        System.out.println("ingrese su ordenada(y)");
        int y = reader.nextInt();  // Read user input
        System.out.println("ingrese su z(z)");
        int z = reader.nextInt();  // Read user input
        Punto first = new Punto();
        Punto second = new Punto(x, y, z);
        if (first.equals(second))
            System.out.println("su punto es el origen");
        else
            System.out.println("su punto es distinto al origen\ncon una distancia de:" + first.distance(second));
        reader.close(); // importante cerrar el reader
    }
}

class Punto { // nombre de la clase
    private int x, y, z;

    // atributos para almacenar el estado.
    public Punto() { // método, define estado inicial,al momento de
        x = y = z = 0; // ser creado, lo llamamos método constructor.
    } // fin de constructor

    public Punto(int _x, int _y, int _z) { // otro constructor
        x = _x;
        y = _y;
        z = _z;
    }

    public int getX() {
        return x;
    }

    public int getY() {
        return y;
    }

    public int getZ() {
        return z;
    }

    public boolean equals(Punto p) {
        if (p == null)
            return false;
        return ((x == p.getX()) && (y == p.getY()) && (z == p.getZ()));
    }

    // Obtiene la distancia sqrt((x1-x2)^2 + (y1-y2)^2)
    public double distance(Punto p) {
        if (p == null)
            return -1; // distancia negativa, punto inexistente
        double xx = x - p.getX(); // pow acepta double asi que lo guardamos de esta manera
        double yy = y - p.getY(); // pow acepta double asi que lo guardamos de esta manera
        double zz = z - p.getZ();
        return (Math.sqrt(Math.pow(xx, 2) + Math.pow(yy, 2) + Math.pow(zz, 2)));
    }
}

**Comment by gopimn** [comment]
Hola Abraham!

Gracias por responder la tarea, 

Genial! pero no te preocupes porque yo siempre le cambio cuando lo pruebo, pude ejecutarlo bien =)! pudiste tu?

```bash
test > javac test.java && java test
########## Jugando con puntos ######## 
ingrese su abscisa(x)
4
ingrese su ordenada(y)
4
ingrese su z(z)
5
su punto es distinto al origen
con una distancia de:7.54983443527075
test > 
```
Acuerdate de la versión de este codigo con herencia! =)

**Comment by infacundo** [comment]
Si profe lo pude correr bien Gracias 😁

Get Outlook para Android<https://aka.ms/AAb9ysg>
________________________________
