### ISSUE TITLE
Ignacio Miranda Miranda || First Task C++ || Hello_World_bot

### ISSUE THREAD

**Issue by IgnacioPotatoe** [gopimn/elo329_1_2022#43]
'''
#include <iostream>
using namespace std;

void hellow(string saludos)
{
    if (saludos == "hola")
        cout<<"hola q tal, soy POO_BOT\n";
    else if(saludos == "chao" || saludos == "adios")
        cout<<"okay un gusto\n";   
    else 
        cout<<"no te entiendo\n";
}
int main(){
    cout<<"solo puede hacer 4 interaciones\n";
    int a= 0;
    while (a<4)
    { 
        string saludos; cin>>saludos;
        hellow(saludos); a++;
    }
    cout<<"fin de programa";
    return 0;
}
'''

**Comment by gopimn** [comment]
xDD faltaba el <iostream>
