### ISSUE TITLE
Gabriel Mamani || First Task  || C++

### ISSUE THREAD

**Issue by nijoko** [gopimn/elo329_1_2022#45]
//c++ "hello world"
#include <iostream>
#include <string>

std::string hello_world(std::string message){
  std::string result = "";
  int i;
  for(i=0;i<message.size();i++){
    int select = (message.size()-1)-i;
    result.push_back(message[select]);
  }
  return result;
}

int main(int argc, char *argv[]){
  std::string output= "dlrow olleH";
  std::cout<<hello_world(output)<<std::endl;
  return 0;
}

**Comment by gopimn** [comment]
buena!
