### ISSUE TITLE
Diego Prokes Herbage

### ISSUE THREAD

**Issue by PH-Diego** [gopimn/elo329_1_2022#9]
import java.util.Scanner;

public class PuntoProgram
{
    public static void main(String [] args)
    {
        int x, y, z;

        Scanner reader = new Scanner(System.in);
        System.out.println("Ingrese la coordenada x de su punto: ");
        x = reader.nextInt();
        System.out.println("Ingrese la coordenada y de su punto: ");
        y = reader.nextInt();
        System.out.println("Ingrese la coordenada z de su punto: ");
        z = reader.nextInt();

        reader.close();

        Punto p1 = new Punto();
        Punto p2 = new Punto(x, y, z); 

        if (p1.equals(p2))
        {
            System.out.println("El punto esta en el origen.");
        } else
        {
            float distance = (float) p1.euclideanDistance(p2);
            System.out.println("La distancia del punto al origen es: " + distance);
        }
        //System.out.println(p1.equals(p2));
        //System.out.println((float)p1.euclideanDistance(p2));
    }
}

class Punto
{
    private int x, y, z;

    // constructores
    public Punto()
    {
        x = 0;
        y = 0;
        z = 0;
    }

    public Punto(int x, int y, int z)
    {
        this.x = x;
        this.y = y;
        this.z = z;
    }

    //getters
    public int getX()
    {
        return this.x;
    }

    public int getY()
    {
        return this.y;
    }

    public int getZ()
    {
        return this.z;
    }

    // determina si dos puntos son el mismo
    public boolean equals(Punto p)
    {
        if((x == p.getX()) && (y == p.getY()) && (z == p.getZ()))
        {
            return true;
        }
        return false;
    }

    // determina la distancia entre 2 puntos
    public double euclideanDistance(Punto p)
    {
        double deltaX = x - p.getX();
        double deltaY = y - p.getY();
        double deltaZ = z - p.getZ();
        double distance = Math.sqrt(Math.pow(deltaX,2) + Math.pow(deltaY,2) + Math.pow(deltaZ,2));
        return distance;
    }
}

**Comment by gopimn** [comment]
Hola Diego,

Gracias por participar, mirate esta [guía](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) para aprender a poner codeblocks en markdown de github y edita tu comentario para que se vea más bonito.

Le cambie el nombre de la clase cuando lo corrí para no cambiar el nombre de mi archivo de prueba:

```bash
test > javac Main.java 
test > java Main
Ingrese la coordenada x de su punto: 
4
Ingrese la coordenada y de su punto: 
4
Ingrese la coordenada z de su punto: 
4
La distancia del punto al origen es: 6.928203
test > java Main
Ingrese la coordenada x de su punto: 
0
Ingrese la coordenada y de su punto: 
0
Ingrese la coordenada z de su punto: 
0
El punto esta en el origen.
test > 
```
Muy bien!
